# Generated by Django 4.1.1 on 2022-10-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactpg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
